defaults:
  - task: RPL_Insert_3DoF
  - _self_

run: train  # train, test or both (not implemented)

train:
  render: False
  run_name:  # PH-90  # If not empty, load and resume this run
  use_neptune: True

test:
  n_epochs: 10
  render: True
  model_id: '284'  # Name of the model to test. '90' loads the latest model, '90_10000' loads the model at 10,000 steps, None for IK
  log_freq: 1  # Interval to log the environment (in timesteps)
  use_neptune: True
  render_speed:  0.75  # 1 is normal speed, 0.5 is half speed, 2 is double speed

neptune:
  project_name: MyResearch/Applied-Dynamics---Peg-in-hole
  api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI3ZjM3ODdiMy00ZmNhLTRkODUtODYyMi1mMGM5MzM5OTk4MWUifQ==
  save_freq: 50_000  # Save the model every n steps
  env_log_freq: 10  # Interval to log the environment (in timesteps)
  log_env: True  #  If true, logs the environment steps
  temp_save_path: tmp/