defaults:
  - task: Insert_Kinova3DoF
  - _self_
  
render: True
test: False

neptune:
  use_neptune: True
  project_name: MyResearch/Applied-Dynamics---Peg-in-hole
  api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI3ZjM3ODdiMy00ZmNhLTRkODUtODYyMi1mMGM5MzM5OTk4MWUifQ==
