defaults:
  - task: RPL_Insert_3DoF
  - _self_
  
render: False
test: False
run_name: PH-90

neptune:
  use_neptune: True
  project_name: MyResearch/Applied-Dynamics---Peg-in-hole
  api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI3ZjM3ODdiMy00ZmNhLTRkODUtODYyMi1mMGM5MzM5OTk4MWUifQ==
  save_freq: 5_000  # Save the model every n steps
  env_log_freq: 10  # Interval to log the environment (in timesteps)
  log_env: True  #  If true, logs the environment steps
  temp_save_path: tmp/