task: 'Insert_Kinova3DoF'

general:
  log_freq: 2  # Save robot state at each # step

rl_hparams:
  episodes: 50  # Total num of episodes
  critic_lr: 0.0001
  actor_lr: 0.0001
  noise_std_dev: 0.2  # Standard dev of OUActionNoise
  tau: 0.001  # Used to update target networks
  action_coeff: 0.01  # coefficient the action will be multiplied by

  buffer:
    gamma: 0.99  # Discount factor for future rewards
    capacity: 200000
    batch_size: 32

  reward:
    reward_min_threshold: -5.0  # NOT CURRENTLY USED
    min_height_threshold: 0.005  # NOT CURRENTLY USED
    reward_weight: 0.04
  

env:
  ...

